server:
  port: 8080

spring:
  application:
    name: base-service

eureka:
    client:
      register-with-eureka : true
      fetch-registry: true
      service-url :
          defaultZone : http://localhost:8761/eureka, http://localhost:8762/eureka, http://localhost:8763/eureka