server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/dowonlee_1/Desktop/git/toy-msa-etc/git-local-repo
        git: #default
          uri: https://github.com/joneconsulting/spring-cloud-config
          default-label: master
#              basedir: /Users/dowonlee/Desktop/Work/tmp/config-repo
#              username: [username]
#              password: [password]
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
